# Generated by Django 5.2.8 on 2025-12-02 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('barber', 'Barber'), ('stylist', 'Stylist'), ('manager', 'Manager'), ('receptionist', 'Receptionist')], default='barber', max_length=20)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='businesses.business')),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='staff_busines_6dc3f1_idx')],
            },
        ),
    ]
